### ISSUE TITLE
Immense WiFi slowdown in home network

### ISSUE THREAD

**Issue by S4ndf1re** [plapointe6/EspMQTTClient#104]
I am using this library on 4 ESP8266. The more devices I start and connect to my home networks WiFi, the slower the WiFi gets. This gets as bad as 0.8 mb/s download speed and 0.1 mb/s upload. Normally (and when none of the 4 devices are on) this is around 40 mb/s download and 30 mb/s upload. 

My initial idea was to let them run 24/7, but apparently, this isn't an option, if the WiFi keeps slowing down this extreme. 

If you have any idea why this kind of error occures, please let me know.

**Comment by EdJoPaTo** [comment]
Can you confirm this library is causing this and not WiFi in general?

I assume your numbers are 40 Mbit/s (or Mbps) download and not MB/s? The Internet download normally is way slower than what WiFi itself can achieve (in good conditions).

Depending on the WiFi Router / WiFi Standard the speed can vary. Older standards are not as well suited for many devices working in parallel but ESPs normally arn't that active.
