### ISSUE TITLE
I want to set/change SSID, Password and Client ID in setup()

### ISSUE THREAD

**Issue by my-reminiscence** [plapointe6/EspMQTTClient#133]
I want to set/change SSID, Password and Client ID in setup() and other functions because WiFi credentials stored in EEPROM which can be changed and client id is dynamically generated.

**Comment by EdJoPaTo** [comment]
why not change them with the constructor?

**Comment by my-reminiscence** [comment]
Because we have some sensors which define or choose from different options.

**Comment by ChuckMash** [comment]
This is possible.
Please see the example called DelayedMQTTClientConfiguration.

https://github.com/plapointe6/EspMQTTClient/blob/master/examples/DelayedMQTTClientConfiguration/DelayedMQTTClientConfiguration.ino#L92-L95

**Comment by my-reminiscence** [comment]
> This is possible. Please see the example called DelayedMQTTClientConfiguration.
> 
> https://github.com/plapointe6/EspMQTTClient/blob/master/examples/DelayedMQTTClientConfiguration/DelayedMQTTClientConfiguration.ino#L92-L95

Thanks @ChuckMash It is working fine now.
