### ISSUE TITLE
Knowing if onConnectionEstablished is called at system startup or after a reconnect

### ISSUE THREAD

**Issue by githubbuh** [plapointe6/EspMQTTClient#14]
plapointe6,

Do I understand correctly that onConnectionEstablished() is the callback for incoming mqtt messages?

If it is the case, I wonder why onConnectionEstablished() subscribes everytime rather than having the subscription in setup().

**Comment by githubbuh** [comment]
plapointe6.

I understand now that onConnectionEstablished() is only called once after successfully connecting to both wifi and mqtt.

I think it would be helpful to modify the example to illustrate how ::subscribe(topic, pointer to function) may be used to specify a function that will process an incoming messages.

It might also be helpful to expose a class property that can be used, for example in onConnectionEstablished, to know if the call is at system startup (i.e. the first time), or because of a reconnect.

Maybe modify the simple example as follows:
`
// ------------------------------------------------------
// function to process incoming mqtt payload
//
// note that this function is connected to the subscriber
// in onConnectionEstablished()
//
// it is in this function that all of the processing of the 
// incoming MQTT payload will be performed
// ------------------------------------------------------
void topicPayloadProcess(String payload)
{
  Serial.println("in topicPayloadProcess"); 
  Serial.println(payload);
  mqttClient.publish("mytest/topic", payload);
}

// onConnectionEstablished() is called _**just once**_ after both 
// the WiFi client and the MQTT are successfully connected
//
// when a reconnect happens, because either the WiFi or MQTT
// client disconnects, onConnectionEstablished() is called again
//
// it is in this function that the MQTT subscriber is initialized
//
// when the subscriber is initialized, it is possible to 
// assign a function to process the topic payload
//
// NOTE : If this function is not implemented, then no subscriber
//        will be initialized, which means that the sketch will NOT
//        process incoming MQTT messages
void onConnectionEstablished()
{   
  // Initilize the subscriber to the topic and provide a function to
  // process the payload
  mqttClient.subscribe("mytopic/test", [](const String & payload) 
  {
      topicPayloadProcess(payload);
  });

  // an example showing that a message can be published from
  // onConnectionEstablished to notify that all is good.
  //
  // Publish a message to topic  (i.e. "mytopic/test")
  // Activate the MQTT retain flag by adding a third parameter of true

  // this is where it would be helpful to know if this is the first time or a reconnect
  // **NOTE to readers** of this comment in _this post_.  The IF statement shown
  // below is illustration only.  There is no reConnect() in the class today.
  if(mqttClient.reConnect())
  {
    mqttClient.publish("mytopic/text",
                                   "onConnectionEstablished() after reconnect"); 
  }
  else
  {
    mqttClient.publish("mytopic/text",
                                   "onConnectionEstablished() during system startup"); 
  }

  // An example of how to execute a delayed instruction, which will
  // delay processing a task without impact to 8266 nodes
  mqttClient.executeDelayed(5 * 1000, []() 
  {
    mqttClient.publish("mtopic/test", "This is a message sent 5 seconds later");
  });
}`

Thanks for the work that you have done to provide this library.  I have been struggling for several weeks now to come up with a sketch that has an availability of better than say 65%.  I haven't figured out yet why mine won't consistently reconnect.   

I am hoping that the EspMQTTClient will be just the ticket!

**Comment by plapointe6** [comment]
Hi,
I like the idea of adding the possibility of knowing if the onConnectionEstablished was called after a connection lost or not. I will take note and maybe add this to the next version.

**Comment by githubbuh** [comment]
plapointe6,

I have found two changes to be very helpful.
1) make serialLogsEnabled public.  It is a capability that can be used anywhere in the sketch.  Justification for exposing: since the sketch is focused on MQTT, makes sense to have access to useful features of the MQTT class.

2) add int mMqttConnectCount and int mqttConnectCount().  if == 1, then original connect.  if > 1 then reconnect.  This is very useful.  In the ping response, my nodes include connect count.  As illustrated below, the node lost its connection and reconnected at 17:34.
`
2019.6.30 15:00:02: {"mode":"diagnostic","event":"ping","sys":"esp32-irr","topic":"irrigation/monitor","action":"notify","msgID":"68f72347.c0178c","version":"2.0.1","ssid":"Hairy Feet","mac":"pending","mclient":"esp32-irr","free":274560,"invalid":0,"connect":1}
2019.6.30 17:34:09: {"mode":"diagnostic","event":"reconnect","sys":"esp32-irr","topic":"irrigation/monitor","action":"notify","version":"2.0.1","ssid":"Hairy Feet","mac":"pending","mclient":"esp32-irr","free":273400,"invalid":0,"connect":2}
`
The modified header.  Please note that this is a down-1 version.

`#ifndef ESP_MQTT_CLIENT_H
#define ESP_MQTT_CLIENT_H

#include <PubSubClient.h>

#ifdef ESP8266

  #include <ESP8266WiFi.h>
  #include <ESP8266WebServer.h>
  #include <ESP8266mDNS.h>
  #include <ESP8266HTTPUpdateServer.h>
  
  #define WebServer ESP8266WebServer
  #define ESPmDNS ESP8266mDNS
  #define ESPHTTPUpdateServer ESP8266HTTPUpdateServer

#else // for ESP32

  #include <WiFiClient.h>
  #include <WebServer.h>
  #include <ESPmDNS.h>
  #include "ESP32HTTPUpdateServer.h"

  #define ESPHTTPUpdateServer ESP32HTTPUpdateServer

#endif

#define MAX_TOPIC_SUBSCRIPTION_LIST_SIZE 10
#define MAX_DELAYED_EXECUTION_LIST_SIZE 10
#define CONNECTION_RETRY_DELAY 10 * 1000

void onConnectionEstablished(); // MUST be implemented in your sketch. Called once everythings is connected (Wifi, mqtt).

typedef void(*ConnectionEstablishedCallback) ();
typedef void(*MessageReceivedCallback) (const String &message);
typedef void(*DelayedExecutionCallback) ();

class EspMQTTClient 
{
private:
  // Wifi related
  bool mWifiConnected;
  unsigned long mLastWifiConnectionAttemptMillis;
  unsigned long mLastWifiConnectionSuccessMillis;
  const char* mWifiSsid;
  const char* mWifiPassword;
  WiFiClient mWifiClient;

  // MQTT related
  bool mMqttConnected;
  unsigned long mLastMqttConnectionMillis;
  const char* mMqttServerIp;
  const short mMqttServerPort;
  const char* mMqttUsername;
  const char* mMqttPassword;
  const char* mMqttClientName;
  bool mMqttCleanSession;
  char* mMqttLastWillTopic;
  char* mMqttLastWillMessage;
  bool mMqttLastWillRetain;

  PubSubClient mMqttClient;

  struct TopicSubscriptionRecord {
    String topic;
    MessageReceivedCallback callback;
  };
  TopicSubscriptionRecord mTopicSubscriptionList[MAX_TOPIC_SUBSCRIPTION_LIST_SIZE];
  byte mTopicSubscriptionListSize;

  // HTTP update server related
  char* mUpdateServerAddress;
  char* mUpdateServerUsername;
  char* mUpdateServerPassword;
  WebServer* mHttpServer;
  ESPHTTPUpdateServer* mHttpUpdater;

  // Delayed execution related
  struct DelayedExecutionRecord {
    unsigned long targetMillis;
    DelayedExecutionCallback callback;
  };
  DelayedExecutionRecord mDelayedExecutionList[MAX_DELAYED_EXECUTION_LIST_SIZE];
  byte mDelayedExecutionListSize = 0;

  // General behaviour related
  ConnectionEstablishedCallback mConnectionEstablishedCallback;
  bool mEnableSerialLogs;
  bool mShowLegacyConstructorWarning;
  
  // fm additions start here
  //bool mMqttReconnect;
  int  mMqttConnectionCount;
  // fm additions end here


public:
  // Wifi + MQTT with no MQTT authentification
  EspMQTTClient(
    const char* wifiSsid, 
    const char* wifiPassword, 
    const char* mqttServerIp, 
    const char* mqttClientName = "ESP8266",
    const short mqttServerPort = 1883);

  // Wifi + MQTT with MQTT authentification
  EspMQTTClient(
    const char* wifiSsid,
    const char* wifiPassword,
    const char* mqttServerIp,
    const char* mqttUsername,
    const char* mqttPassword,
    const char* mqttClientName = "ESP8266",
    const short mqttServerPort = 1883);

  // Only MQTT handling (no wifi), with MQTT authentification
  EspMQTTClient(
    const char* mqttServerIp,
    const short mqttServerPort,
    const char* mqttUsername,
    const char* mqttPassword,
    const char* mqttClientName = "ESP8266");

  // Only MQTT handling without MQTT authentification
  EspMQTTClient(
    const char* mqttServerIp,
    const short mqttServerPort,
    const char* mqttClientName = "ESP8266");

  // Legacy constructor for version 1.3 - WILL BE DELETED SOON OR LATER
  EspMQTTClient(
    const char* wifiSsid, 
    const char* wifiPassword,
    ConnectionEstablishedCallback connectionEstablishedCallback,
    const char* mqttServerIp, 
    const short mqttServerPort = 1883,
    const char* mqttUsername = NULL, 
    const char* mqttPassword = NULL, 
    const char* mqttClientName = "ESP8266",
    const bool enableWebUpdater = true, 
    const bool enableSerialLogs = true);

  // Legacy constructor for version <= 1.2 - WILL BE DELETED SOON OR LATER
  EspMQTTClient(
    const char* wifiSsid, 
    const char* wifiPassword, 
    const char* mqttServerIp,
    const short mqttServerPort, 
    const char* mqttUsername, 
    const char* mqttPassword,
    const char* mqttClientName, 
    ConnectionEstablishedCallback connectionEstablishedCallback,
    const bool enableWebUpdater = true, 
    const bool enableSerialLogs = true);

  ~EspMQTTClient();

  // Optionnal functionnalities
  void enableDebuggingMessages(const bool enabled = true); // Allow to display usefull debugging messages. Can be set to false to disable them during program execution
  void enableHTTPWebUpdater(const char* username, const char* password, const char* address = "/"); // Activate the web updater, must be set before the first loop() call.
  void enableHTTPWebUpdater(const char* address = "/"); // Will set user and password equal to mMqttUsername and mMqttPassword
  void enableMQTTPersistence(); // Tell the broker to establish a persistant connection. Disabled by default. Must be called before the fisrt loop() execution
  void enableLastWillMessage(const char* topic, const char* message, const bool retain = false); // Must be set before the first loop() call.

  // Main loop, to call at each sketch loop()
  void loop();

  // fm start here
  int  mqttConnectionCount();
  bool serialLogsEnabled();
  // bool mqttReconnect();
  // fm end here
 
  // MQTT related
  void publish(const String &topic, const String &payload, bool retain = false);
  void subscribe(const String &topic, MessageReceivedCallback messageReceivedCallback);
  void unsubscribe(const String &topic);   //Unsubscribes from the topic, if it exists, and removes it from the CallbackList.

  // Other
  void executeDelayed(const long delay, DelayedExecutionCallback callback);

  inline bool isConnected() const { return mWifiConnected && mMqttConnected; };
  inline void setOnConnectionEstablishedCallback(ConnectionEstablishedCallback callback) { mConnectionEstablishedCallback = callback; }; // Default to onConnectionEstablished, you might want to override this for special cases like two MQTT connections in the same sketch

private:
  void connectToWifi();
  void connectToMqttBroker();
  void mqttMessageReceivedCallback(char* topic, byte* payload, unsigned int length);
};

#endif`

Modified cpp, which is also a down 1.
`#include "EspMQTTClient.h"


// =============== Constructor / destructor ===================

// MQTT only (no wifi connection attempt)
EspMQTTClient::EspMQTTClient(
  const char* mqttServerIp,
  const short mqttServerPort,
  const char* mqttClientName) :
  EspMQTTClient(NULL, NULL, mqttServerIp, NULL, NULL, mqttClientName, mqttServerPort)
{
}
EspMQTTClient::EspMQTTClient(
  const char* mqttServerIp,
  const short mqttServerPort,
  const char* mqttUsername,
  const char* mqttPassword,
  const char* mqttClientName) :
  EspMQTTClient(NULL, NULL, mqttServerIp, mqttUsername, mqttPassword, mqttClientName, mqttServerPort)
{
}

// Wifi and MQTT handling
EspMQTTClient::EspMQTTClient(
  const char* wifiSsid,
  const char* wifiPassword,
  const char* mqttServerIp,
  const char* mqttClientName,
  const short mqttServerPort) :
  EspMQTTClient(wifiSsid, wifiPassword, mqttServerIp, NULL, NULL, mqttClientName, mqttServerPort)
{
}

// Warning : for old constructor support, this will be deleted soon or later
EspMQTTClient::EspMQTTClient(
  const char* wifiSsid, 
  const char* wifiPassword, 
  const char* mqttServerIp,
  const short mqttServerPort, 
  const char* mqttUsername, 
  const char* mqttPassword,
  const char* mqttClientName, 
  ConnectionEstablishedCallback connectionEstablishedCallback,
  const bool enableWebUpdater, 
  const bool enableSerialLogs) :
  EspMQTTClient(wifiSsid, wifiPassword, mqttServerIp, mqttUsername, mqttPassword, mqttClientName, mqttServerPort)
{
  if (enableWebUpdater)
    enableHTTPWebUpdater();

  if (enableSerialLogs)
    enableDebuggingMessages();

  setOnConnectionEstablishedCallback(connectionEstablishedCallback);

  mShowLegacyConstructorWarning = true;
}

// Warning : for old constructor support, this will be deleted soon or later
EspMQTTClient::EspMQTTClient(
  const char* wifiSsid, 
  const char* wifiPassword,
  ConnectionEstablishedCallback connectionEstablishedCallback, 
  const char* mqttServerIp, 
  const short mqttServerPort,
  const char* mqttUsername,
  const char* mqttPassword, 
  const char* mqttClientName,
  const bool enableWebUpdater,
  const bool enableSerialLogs) :
  EspMQTTClient(wifiSsid, wifiPassword, mqttServerIp, mqttUsername, mqttPassword, mqttClientName, mqttServerPort)
{
  if (enableWebUpdater)
    enableHTTPWebUpdater();

  if (enableSerialLogs)
    enableDebuggingMessages();

  setOnConnectionEstablishedCallback(connectionEstablishedCallback);

  mShowLegacyConstructorWarning = true;
}

EspMQTTClient::EspMQTTClient(
  const char* wifiSsid,
  const char* wifiPassword,
  const char* mqttServerIp,
  const char* mqttUsername,
  const char* mqttPassword,
  const char* mqttClientName,
  const short mqttServerPort) :
  mWifiSsid(wifiSsid),
  mWifiPassword(wifiPassword),
  mMqttServerIp(mqttServerIp),
  mMqttUsername(mqttUsername),
  mMqttPassword(mqttPassword),
  mMqttClientName(mqttClientName),
  mMqttServerPort(mqttServerPort),
  mMqttClient(mqttServerIp, mqttServerPort, mWifiClient)
{
  // WiFi connection
  mWifiConnected = false;
  mLastWifiConnectionAttemptMillis = 0;
  mLastWifiConnectionSuccessMillis = 0;

  // MQTT client
  mTopicSubscriptionListSize = 0;
  mMqttConnected = false;
  mLastMqttConnectionMillis = 0;
  mMqttLastWillTopic = 0;
  mMqttLastWillMessage = 0;
  mMqttLastWillRetain = false;
  mMqttCleanSession = true;
  mMqttClient.setCallback([this](char* topic, byte* payload, unsigned int length) {this->mqttMessageReceivedCallback(topic, payload, length);});

  // fm addition start
  // startup state

  // set the reconnect to false 
  // it will be false until the first reconnect
  // at which point it will become true
  //mMqttReconnect = false;
  
  // the connection counter is initialized to zero
  // and increments every time onConnectionEstablished is called 
  mMqttConnectionCount= 0;
  // fm addition end
  
  // Web updater
  mUpdateServerAddress = NULL;
  mHttpServer = NULL;
  mHttpUpdater = NULL;

  // other
  mEnableSerialLogs = false;
  mConnectionEstablishedCallback = onConnectionEstablished;
  mShowLegacyConstructorWarning = false;
}

EspMQTTClient::~EspMQTTClient()
{
  if (mHttpServer != NULL)
    delete mHttpServer;
  if (mHttpUpdater != NULL)
    delete mHttpUpdater;
}


// =============== Configuration functions, most of them must be called before the first loop() call ==============

void EspMQTTClient::enableDebuggingMessages(const bool enabled)
{
  mEnableSerialLogs = enabled;
}

void EspMQTTClient::enableHTTPWebUpdater(const char* username, const char* password, const char* address)
{
  if (mHttpServer == NULL)
  {
    mHttpServer = new WebServer(80);
    mHttpUpdater = new ESPHTTPUpdateServer();
    mUpdateServerUsername = (char*)username;
    mUpdateServerPassword = (char*)password;
    mUpdateServerAddress = (char*)address;
  }
  else if (mEnableSerialLogs)
    Serial.print("SYS! You can't call enableHTTPWebUpdater() more than once !\n");
}

void EspMQTTClient::enableHTTPWebUpdater(const char* address)
{
  if(mMqttUsername == NULL || mMqttPassword == NULL)
    enableHTTPWebUpdater("", "", address);
  else
    enableHTTPWebUpdater(mMqttUsername, mMqttPassword, address);
}

void EspMQTTClient::enableMQTTPersistence()
{
  mMqttCleanSession = false;
}

void EspMQTTClient::enableLastWillMessage(const char* topic, const char* message, const bool retain)
{
  mMqttLastWillTopic = (char*)topic;
  mMqttLastWillMessage = (char*)message;
  mMqttLastWillRetain = retain;
}


// =============== Public functions =================

// fm start here
// return the reconnect status, which will be false
// at start up and true after any subsequent reconnect
//bool EspMQTTClient::mqttReconnect()
//{
//	return mMqttReconnect;
//}

// return the number of times the client has connected
// the counter is incremented before calling
// onConnectionEstablished();
int EspMQTTClient::mqttConnectionCount()
{
	return mMqttConnectionCount;
}

// getter for the serial log enabled indicator
// sort of a stretch, but will be helpful to 
// use across the application
bool EspMQTTClient::serialLogsEnabled()
{
	return mEnableSerialLogs;
}
// fm end here


void EspMQTTClient::loop()
{
  long currentMillis = millis();
  
  if (WiFi.status() == WL_CONNECTED)
  {
    // If we just being connected to wifi
    if (!mWifiConnected)
    {
      if (mEnableSerialLogs)
        Serial.printf("WiFi: Connected, ip : %s\n", WiFi.localIP().toString().c_str());

      mLastWifiConnectionSuccessMillis = millis();
      
      // Config of web updater
      if (mHttpServer != NULL)
      {
        MDNS.begin(mMqttClientName);
        mHttpUpdater->setup(mHttpServer, mUpdateServerAddress, mUpdateServerUsername, mUpdateServerPassword);
        mHttpServer->begin();
        MDNS.addService("http", "tcp", 80);
      
        if (mEnableSerialLogs)
          Serial.printf("WEB: Updater ready, open http://%s.local in your browser and login with username '%s' and password '%s'.\n", mMqttClientName, mUpdateServerUsername, mUpdateServerPassword);
      }
  
      mWifiConnected = true;
    }
    
    // MQTT handling
    if (mMqttClient.connected())
      mMqttClient.loop();
    else
    {
      if (mMqttConnected)
      {
        if (mEnableSerialLogs)
          Serial.println("MQTT! Lost connection.");
        
        mTopicSubscriptionListSize = 0;
        mMqttConnected = false;
      }
      
      if (currentMillis - mLastMqttConnectionMillis > CONNECTION_RETRY_DELAY || mLastMqttConnectionMillis == 0)
        connectToMqttBroker();
    }
      
    // Web updater handling
    if (mHttpServer != NULL)
      mHttpServer->handleClient();
  }
  else // If we are not connected to wifi
  {
    if (mWifiConnected) 
    {
      if (mEnableSerialLogs)
        Serial.println("WiFi! Lost connection.");
      
      mWifiConnected = false;

      // If we handle wifi, we force disconnection to clear the last connection
      if (mWifiSsid != NULL)
        WiFi.disconnect();
    }
    
    // We retry to connect to the wifi if we handle it and there was no attempt since the last connection lost
    if (mWifiSsid != NULL && (mLastWifiConnectionAttemptMillis == 0 || mLastWifiConnectionSuccessMillis > mLastWifiConnectionAttemptMillis))
      connectToWifi();
  }
  
  // Delayed execution handling
  if (mDelayedExecutionListSize > 0)
  {
    long currentMillis = millis();
    
    for(byte i = 0 ; i < mDelayedExecutionListSize ; i++)
    {
      if (mDelayedExecutionList[i].targetMillis <= currentMillis)
      {
        (*mDelayedExecutionList[i].callback)();
        for(int j = i ; j < mDelayedExecutionListSize-1 ; j++)
          mDelayedExecutionList[j] = mDelayedExecutionList[j + 1];
        mDelayedExecutionListSize--;
        i--;
      }
    }
  }

  // Old constructor support warning
  if (mEnableSerialLogs && mShowLegacyConstructorWarning)
  {
    mShowLegacyConstructorWarning = false;
    Serial.print("SYS! You are using a constructor that will be deleted soon, please update your code with the new construction format.\n");
  }

}

void EspMQTTClient::publish(const String &topic, const String &payload, bool retain)
{
  mMqttClient.publish(topic.c_str(), payload.c_str(), retain);

  if (mEnableSerialLogs)
    Serial.printf("MQTT << [%s] %s\n", topic.c_str(), payload.c_str());
}

void EspMQTTClient::subscribe(const String &topic, MessageReceivedCallback messageReceivedCallback)
{
  // Check the possibility to add a new topic
  if (mTopicSubscriptionListSize >= MAX_TOPIC_SUBSCRIPTION_LIST_SIZE) 
  {
    if (mEnableSerialLogs)
      Serial.println("MQTT! Subscription list is full, ignored.");
    return;
  }

  // Check the duplicate of the subscription to the topic
  bool found = false;
  for (int i = 0; i < mTopicSubscriptionListSize && !found; i++)
    found = mTopicSubscriptionList[i].topic.equals(topic);

  if (found) 
  {
    if (mEnableSerialLogs)
      Serial.printf("MQTT! Subscribed to [%s] already, ignored.\n", topic.c_str());
    return;
  }

  // All checks are passed - do the job
  mMqttClient.subscribe(topic.c_str());
  mTopicSubscriptionList[mTopicSubscriptionListSize++] = { topic, messageReceivedCallback };
  
  if (mEnableSerialLogs)
    Serial.printf("MQTT: Subscribed to [%s]\n", topic.c_str());
}

void EspMQTTClient::unsubscribe(const String &topic)
{
  bool found = false;

  for (int i = 0; i < mTopicSubscriptionListSize; i++)
  {
    if (!found)
    {
      if (mTopicSubscriptionList[i].topic.equals(topic))
      {
        found = true;
        mMqttClient.unsubscribe(topic.c_str());
        if (mEnableSerialLogs)
          Serial.printf("MQTT: Unsubscribed from %s\n", topic.c_str());
      }
    }

    if (found)
    {
      if ((i + 1) < MAX_TOPIC_SUBSCRIPTION_LIST_SIZE)
        mTopicSubscriptionList[i] = mTopicSubscriptionList[i + 1];
    }
  }

  if (found)
    mTopicSubscriptionListSize--;
  else if (mEnableSerialLogs)
    Serial.println("MQTT! Topic cannot be found to unsubscribe, ignored.");
}

void EspMQTTClient::executeDelayed(const long delay, DelayedExecutionCallback callback)
{
  if (mDelayedExecutionListSize < MAX_DELAYED_EXECUTION_LIST_SIZE)
  {
    DelayedExecutionRecord delayedExecutionRecord;
    delayedExecutionRecord.targetMillis = millis() + delay;
    delayedExecutionRecord.callback = callback;
    
    mDelayedExecutionList[mDelayedExecutionListSize] = delayedExecutionRecord;
    mDelayedExecutionListSize++;
  }
  else if (mEnableSerialLogs)
    Serial.printf("SYS! The list of delayed functions is full.\n");
}


// ================== Private functions ====================-

void EspMQTTClient::connectToWifi()
{
  WiFi.mode(WIFI_STA);
  WiFi.begin(mWifiSsid, mWifiPassword);

  if (mEnableSerialLogs)
    Serial.printf("\nWiFi: Connecting to %s ... \n", mWifiSsid);
  
  mLastWifiConnectionAttemptMillis = millis();
}

void EspMQTTClient::connectToMqttBroker()
{
  if (mEnableSerialLogs)
    Serial.printf("MQTT: Connecting to broker @%s ... ", mMqttServerIp);

  if (mMqttClient.connect(mMqttClientName, mMqttUsername, mMqttPassword, mMqttLastWillTopic, 0, mMqttLastWillRetain, mMqttLastWillMessage, mMqttCleanSession))
  {
    mMqttConnected = true;
	
	// fm starts here
	// increment the counter before calling the
	// onConnectionEstablished method
	mMqttConnectionCount++;
	
	// set the mReconnect to true if this is NOT
	// the first time calling onConnectionEstablished()
	//if(mMqttConnectionCount > 1)
	//{
	//	mMqttReconnect = true;
	//}
	// fm ends here
    
    if (mEnableSerialLogs)
	{
        Serial.println("ok.");
//		Serial.print("Connection count: ");
//		Serial.println(mMqttConnectionCount);
//		Serial.print("Reconnect: ");
//		Serial.println(mMqttReconnect);
	}	 

    (*mConnectionEstablishedCallback)();
	
  }
  else if (mEnableSerialLogs)
  {
    Serial.print("unable to connect, ");

    switch (mMqttClient.state())
    {
      case -4:
        Serial.println("MQTT_CONNECTION_TIMEOUT");
        break;
      case -3:
        Serial.println("MQTT_CONNECTION_LOST");
        break;
      case -2:
        Serial.println("MQTT_CONNECT_FAILED");
        break;
      case -1:
        Serial.println("MQTT_DISCONNECTED");
        break;
      case 1:
        Serial.println("MQTT_CONNECT_BAD_PROTOCOL");
        break;
      case 2:
        Serial.println("MQTT_CONNECT_BAD_CLIENT_ID");
        break;
      case 3:
        Serial.println("MQTT_CONNECT_UNAVAILABLE");
        break;
      case 4:
        Serial.println("MQTT_CONNECT_BAD_CREDENTIALS");
        break;
      case 5:
        Serial.println("MQTT_CONNECT_UNAUTHORIZED");
        break;
    }
  }
  
  mLastMqttConnectionMillis = millis();
}

void EspMQTTClient::mqttMessageReceivedCallback(char* topic, byte* payload, unsigned int length)
{
  // Convert the payload into a String
  // First, We ensure that we dont bypass the maximum size of the PubSubClient library buffer that originated the payload
  // This buffer has a maximum length of MQTT_MAX_PACKET_SIZE and the payload begin at "headerSize + topicLength + 1"
  unsigned int strTerminationPos;
  if (strlen(topic) + length + 9 >= MQTT_MAX_PACKET_SIZE)
  {
    strTerminationPos = length - 1;

    if (mEnableSerialLogs)
      Serial.print("MQTT! Your message may be truncated, please change MQTT_MAX_PACKET_SIZE of PubSubClient.h to a higher value.\n");
  }
  else
    strTerminationPos = length;

  // Second, we add the string termination code at the end of the payload and we convert it to a String object
  payload[strTerminationPos] = '\0';
  String payloadStr((char*)payload);

  // Logging
  if (mEnableSerialLogs)
    Serial.printf("MQTT >> [%s] %s\n", topic, payloadStr.c_str());

  // Send the message to subscribers
  for (int i = 0 ; i < mTopicSubscriptionListSize ; i++)
  {
    if (mTopicSubscriptionList[i].topic.equals(topic))
      (*mTopicSubscriptionList[i].callback)(payloadStr); // Call the callback
  }
}
`

**Comment by plapointe6** [comment]
Please use the markdown syntax for formatting code when you copy/paste it on github.

I like your propositions. If you need to know id the Serial logs are enabled or not, it's better to add an accessor the the class (there is already a setter).

I also like your proposition of adding a member "mqttConnectCount".

It would be easier for me to review your code if you submit a pull request of the proposed changes instead of putting the whole code in this issue.,

Thanks for you contribution.

**Comment by githubbuh** [comment]
As you have suggested, i will submit a pull request.

**Comment by plapointe6** [comment]
This feature has been added to the 1.7.0 release.
