### ISSUE TITLE
Solving the problem with connecting to Wi-Fi

### ISSUE THREAD

**Issue by PiterKh** [plapointe6/EspMQTTClient#2]
Hello!
I had problems connecting to the network via Wi-Fi.
The solution was to add the WiFi.waitForConnectResult () function to the void EspMQTTClient :: connectToWifi () method.
Now it works for me like this:

void EspMQTTClient :: connectToWifi ()
{
WiFi.mode (WIFI_STA);
WiFi.begin (mWifiSsid.c_str (), mWifiPassword.c_str ());

if (mEnableSerialLogs)
Serial.printf ("\ nConnection to% s", mWifiSsid.c_str ());

WiFi.waitForConnectResult ();

mLastWifiConnectionMillis = millis ();
}

Best regards, Peter

**Comment by PiterKh** [comment]
I use ESP-12F.

**Comment by plapointe6** [comment]
WaitForConnectionResult() loop until the wifi status become something else than DISCONECTED (https://github.com/esp8266/Arduino/blob/fcf2ac5d3de6c17fe177e16ccd1a2789826c2aa0/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp#L367)

I will need more details of the issues you encoutered as the goal of EspMQTTClient is to provide solution to handle WIFI and MQTT connection without blocking the entire sketch when connecting or when there is a connection lost. This allow other task to be done in your sketch wile connecting. For exemple, you could blink a led while waiting for a connection and more.

**Comment by PiterKh** [comment]
Before:
![image](https://user-images.githubusercontent.com/46559639/51019942-f1a1de00-158d-11e9-9aa0-324a3cda43f9.png)
![image](https://user-images.githubusercontent.com/46559639/51019954-fc5c7300-158d-11e9-9056-481c82baa0c2.png)

After:
![image](https://user-images.githubusercontent.com/46559639/51019963-0a11f880-158e-11e9-8bc3-1ce2904a91ac.png)
![image](https://user-images.githubusercontent.com/46559639/51019970-126a3380-158e-11e9-9941-e38048daa4bb.png)

**Comment by PiterKh** [comment]
> WaitForConnectionResult() loop until the wifi status become something else than DISCONECTED (https://github.com/esp8266/Arduino/blob/fcf2ac5d3de6c17fe177e16ccd1a2789826c2aa0/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp#L367)
> 
> I will need more details of the issues you encoutered as the goal of EspMQTTClient is to provide solution to handle WIFI and MQTT connection without blocking the entire sketch when connecting or when there is a connection lost. This allow other task to be done in your sketch wile connecting. For exemple, you could blink a led while waiting for a connection and more.

Unfortunately, to solve the problem of blocking in this way will not work. In any case, the connection takes time, which blocks the main task loop. For critical tasks it is better to use the “time ticker” (https://circuits4you.com/2018/01/02/esp8266-timer-ticker-example/)

**Comment by plapointe6** [comment]
With version 1.2, I think this issue will be fixed. Feel free to re-open the issue if it's not the case.
