### ISSUE TITLE
EspMQTTClient dynamic configuration

### ISSUE THREAD

**Issue by rumvit** [plapointe6/EspMQTTClient#26]
Hey. I have a good start of your class EspMQTTClient on the esp8266 platform .But I would like to have to adjust the connection settings after reading the SD card.Please tell me how can I change the connection settings to WIFI and MQTT broker in the code of the setup function?

**Comment by plapointe6** [comment]
You could use a pointer to a EspMQTTClient and assign it in the setup() function with new.

```c++
EspMQTTClient* client;

setup() {
client = new EspMQTTClient(here fill your parameters as usual);
}
```

**Comment by rumvit** [comment]
Thanks a lot.Everything seems to be obtained as wanted. Very good job.

**Comment by Sperryfreak01** [comment]
I get the following compile error when I attempt this solution.  Any recommendations?

```src/main.cpp:93:10: error: request for member 'enableDebuggingMessages' in 'client', which is of pointer type 'EspMQTTClient*' (maybe you meant to use '->' ?)```

My code is 
main.h
```EspMQTTClient* client;```

main.cpp

```
 client = new EspMQTTClient(
    WIFI_SSID, // TODO #1 Change to allow user to set wifi password
    WIFI_PASSWORD,
    "url.com",  // MQTT Broker server ip
    MQTT_USER,   // Can be omitted if not needed
    MQTT_PASSWORD,   // Can be omitted if not needed
    mqttuser,     // Client name that uniquely identify your device  #TODO #2 make MQTT login client name dynamic somehow
    1883              // The MQTT port, default to 1883. this line can be omitted
  );

  // Optional functionalities of EspMQTTClient
  client.enableDebuggingMessages(); // Enable debugging messages sent to serial output
  client.enableHTTPWebUpdater(); // Enable the web updater. User and password default to values of MQTTUsername and MQTTPassword. These can be overridden with enableHTTPWebUpdater("user", "password").
  client.enableOTA(); // Enable OTA (Over The Air) updates. Password defaults to MQTTPassword. Port is the default OTA port. Can be overridden with enableOTA("password", port).
  client.enableLastWillMessage(deviceChannel, "Disconnected");  // You can activate the retain flag by setting the third parameter to true
```

**Comment by Sperryfreak01** [comment]
I am only slightly less dumb than I look 😁 

For anyone else that comes this way, make sure to refer to it via `client->[method]` instead of client.[method] before you updated it to be dynamic.  I'm not great with pointers so took me a bit to understand the error message.
