### ISSUE TITLE
Make Wifi connection status public

### ISSUE THREAD

**Issue by erndev** [plapointe6/EspMQTTClient#27]
Could it be possible to add public methods to access `mWifiConnected` and `mMqttConnected`?

it would be useful in order to show status information when wifi is connected but the broker is not.

**Comment by plapointe6** [comment]
Sure, it's possible and pretty easy to do, I will take note to this and add that to the next release. Or you can do a pull resquest and I will merge it.

**Comment by plapointe6** [comment]
This feature has been added to the 1.7.0 release.
