### ISSUE TITLE
Publish fails secretly on too long message

### ISSUE THREAD

**Issue by JenswBE** [plapointe6/EspMQTTClient#30]
First of all, thanks for the awesome library!

Currently, the return value of the publish call is not handled:

https://github.com/plapointe6/EspMQTTClient/blob/eda500e39dee0bacd4d2b05b8760613a3b039121/src/EspMQTTClient.cpp#L287

Therefore, in case your message is too long, it will fail secretly.

Would it be possible to either return the status (boolean) in your publish function or mention this failure in the debug message?

**Comment by plapointe6** [comment]
It's a great idea ! I will definitely do that, thanks for pointing this out.

**Comment by plapointe6** [comment]
This feature has been added to the 1.7.0 release.
