### ISSUE TITLE
Esp32 mqtt over websocket?

### ISSUE THREAD

**Issue by soheils2** [plapointe6/EspMQTTClient#39]
Hi is there any way your code connect mqtt over "ws://" cause this is what I've looked everywhere and found nothing with any library or add-on!

Can you help me with this?

*Ps:
I also ran to some s.hit from espressif called mqtt-clinet.h. That i didn't succed to run it correctly (somehow event handlesr are not implimented !
Im tired of searching and founding literally nothing pensive

espressif/arduino-esp32#3639

**Comment by plapointe6** [comment]
The EspMQTTClient is based on the PubSubClient library for communications.
So, if PubSubClient supports MQTT over WebSocket, EspMQTTClient will be able to do it.

However, the question has been anwsered in the past years and it seems that it's not supported.
See https://github.com/knolleary/pubsubclient/issues/114

If you find a way to uses websockets over PubSubClient, please tell me and I will help you to implements that in EspMQTTClient.

Regards
