### ISSUE TITLE
Can I higher up MAX_TOPIC_SUBSCRIPTION_LIST_SIZE?

### ISSUE THREAD

**Issue by StephanMeijer** [plapointe6/EspMQTTClient#42]
```
#define MAX_TOPIC_SUBSCRIPTION_LIST_SIZE 10
```

**Comment by MoosHam** [comment]
This is a great point, was pulling my hair out over this :-)

Is this the setting that is preventing me to subscribe to more than 10 topics?
Can I jsut change that?
Why is it set to 10, are there downsides when increasing to 20 for example?

thanks,
MoosHam

**Comment by plapointe6** [comment]
@StephanMeijer @MoosHam, is it enough if I increase that to 20 ? I tought that 10 was enough for everyone, no the case so I will increase it.

**Comment by StephanMeijer** [comment]
It would be better to be able to increase it from outside the library.

**Comment by StephanMeijer** [comment]
Like maybe to give it as a property when the `Client`-object is being initiated.

**Comment by plapointe6** [comment]
Yes, but this will lead to dynamic allocation of memory, I prefer to avoid that with microcontrollers when I can. However, maybe we are in a case where it's better to do so. I will think about that.

**Comment by StephanMeijer** [comment]
I trust your expertise in this.
Is there any way we can perhaps wrap the definition on your side in a `IFDEF`, so we can define the value on our side? Or doesn't it work that way?

**Comment by plapointe6** [comment]
Yes, it's a good idea, I will do so right away.

**Comment by plapointe6** [comment]
In fact, I think that it is not necessary. Just do that after the EspMQTTClient.h include : 
```c++
#ifdef MAX_TOPIC_SUBSCRIPTION_LIST_SIZE
#undef MAX_TOPIC_SUBSCRIPTION_LIST_SIZE
#define MAX_TOPIC_SUBSCRIPTION_LIST_SIZE 20
#endif
```

**Comment by StephanMeijer** [comment]
<img width="361" alt="Screenshot 2020-03-15 at 12 53 12" src="https://user-images.githubusercontent.com/3169264/76700861-03b06c80-66bc-11ea-8905-b92d1d84805a.png">
<img width="309" alt="Screenshot 2020-03-15 at 12 52 57" src="https://user-images.githubusercontent.com/3169264/76700863-057a3000-66bc-11ea-9afe-6ac8697a0ee4.png">
Does not seem to work..
