### ISSUE TITLE
Retained messaging

### ISSUE THREAD

**Issue by StephanMeijer** [plapointe6/EspMQTTClient#52]
https://mosquitto.org/man/mqtt-7.html

I am not a MQTT expert, so I'll just ask.

_Is there any way implementing 'retained messages', so I get the most recent after reconnecting with MQTT?_

**Comment by plapointe6** [comment]
Yes you can.
When calling `publish`, you can set the retain flag to true.
```c++
bool publish(const String &topic, const String &payload, bool retain = false);
```

**Comment by StephanMeijer** [comment]
Great.
