### ISSUE TITLE
Allow setting the rate of the MQTT_PINGREQ

### ISSUE THREAD

**Issue by pberna67** [plapointe6/EspMQTTClient#57]
I'm using the library with a charging MQTT broker, that charges the MQTT_PINGREQ message too. I recommend to make possible, at the application layer, to configure the rate of the MQTT_PINGREQ .
Anyone know where to configure it in the present library version ?

**Comment by plapointe6** [comment]
Hello @pberna67,

Is your needs are linked whit the `setKeepAlive()` function of Pubsubclient ? 
https://github.com/knolleary/pubsubclient

`The keepalive interval is set to 15 seconds by default. This is configurable via MQTT_KEEPALIVE in PubSubClient.h or can be changed by calling PubSubClient::setKeepAlive(keepAlive).`

If yes, I will provide a function from `EspMQTTClient` to set this.

Regards

**Comment by plapointe6** [comment]
I added the setKeepAlive method.
