### ISSUE TITLE
Automatic assigment of client name

### ISSUE THREAD

**Issue by Miguelucho** [plapointe6/EspMQTTClient#58]
in the client section:
EspMQTTClient client(
  ...
  "TestClient"      // Client name that uniquely identify your device
);

Is there a way to define "TestClient" as a variable=string+MAC outside the constructor?

I explain. For example I am doing a project called UFO and I have 30 devices that I want to connect, but I don't want to make up 30 names for each one. I would like to change ''TestClient" for a variable = string + MAC, where string would be for example UFO and MAC would be the device's MAC address and thus obtain something like: NAME = "UFO:5ACF7F0B98D8''.

So the string would tell me which project my device is related to and the MAC would give me a client name that uniquely identify my device.

THANKS.

**Comment by ajaybnl** [comment]
**Solution:**

Open espMqttClient.cpp > 

Search line " mMqttClient("

After **{** paste these lines:

_char uid[8];	
String(ESP.getChipId()).toCharArray(uid,8);

//char uid[16];
//String(WiFi.macAddress()).toCharArray(uid,20);

mMqttClientName=uid;_


**Done.**

To Read in Serial :  
Search "void EspMQTTClient::connectToMqttBroker()" and after "if (mEnableSerialLogs){" add these lines:

_Serial.printf("MQTT: Unique Client Name: %s\n",mMqttClientName);_


**Now you will see Client Name in Serial Output (If Enabled).**

**Comment by plapointe6** [comment]
Hello, 

> Is there a way to define "TestClient" as a variable=string+MAC outside the constructor?

Please see this reply : https://github.com/plapointe6/EspMQTTClient/issues/26#issuecomment-532224824

**Comment by ajaybnl** [comment]
It would be better to have an auto assigned client name for everybody.

Btw You should add a client isConnected check and esp reset code in the loop! For safety.

Check every 30 seconds:
If(!client.isConnected) count++; else count=0;
If(count>4)ESP.reset();

**Comment by plapointe6** [comment]
> Btw You should add a client isConnected check and esp reset code in the loop! For safety.
> 
> Check every 30 seconds:
> If(!client.isConnected) count++; else count=0;
> If(count>4)ESP.reset();

Instead of doing an ESP.reset(), I reset the wifi radio by doing a WiFi.disconnect(true) if I loose the WiFi connection.

> It would be better to have an auto assigned client name for everybody.

Maybe I will auto-assign the client name if none is provided. However, providing a client name is usefull because it is also used by DNS assignation to easily finds your device in the network.
