### ISSUE TITLE
QoS

### ISSUE THREAD

**Issue by pberna67** [plapointe6/EspMQTTClient#68]
Dear Developer

I would like to introduce the QoS service for the topic
The idea is to make available the QoS parameter 0,1,2 for each mqtt topic

Thanks

**Comment by plapointe6** [comment]
I added the possibility to specify the qos when subscrbing (not releashed yet). However, the PubSubClient library does not support QOS when publishing, so I can't add this functionnality.

**Comment by plapointe6** [comment]
Functionnality added with the 1.11.0 release.
