### ISSUE TITLE
New release, cannot get example or old code to work

### ISSUE THREAD

**Issue by ntableman** [plapointe6/EspMQTTClient#7]
Can you guide me on what changed in this, so I cam update my code? Your example won't compile for me even.

**Comment by grafspirt** [comment]
There was a change of the class constructor attributes sequence to make available short forms when only a minimum of necessary attributes may be passed. Like:
```
EspMQTTClient client(
  "ssid",                 // Wifi ssid
  "pass",                 // Wifi password
  onConnectionEstablished,// MQTT connection established callback
  "ip"                    // MQTT broker ip
);
```

The long form taking all attributes has become as follows:
```
EspMQTTClient client(
  "ssid",                 // Wifi ssid
  "pass",                 // Wifi password
  onConnectionEstablished,// Connection established callback
  "ip",                   // MQTT broker ip
  1883,                   // MQTT broker port
  "mqttusr",              // MQTT username
  "mqttpass",             // MQTT password
  "test",                 // Client name
  true,                   // Enable web updater
  true                    // Enable debug messages
);
```
The attached to the package example code initiates the class object this way and is compiled ok.
Please have a try with the an example from the branch and report a problem if any appears.

**Comment by grafspirt** [comment]
If there are no objections and new inputs I assume to close the topic.

**Comment by plapointe6** [comment]
Sorry for late response, I had health problems :(
I made minor changes to prepare for v1.3 release.
One of them is to support old constructor formulation (see commit 4ea0455957734a6554bcf8961c618f38f57406e6)

Regards
