### ISSUE TITLE
setMaxPacketSize not working

### ISSUE THREAD

**Issue by bas-eng** [plapointe6/EspMQTTClient#70]
The setMaxPacketSize is not working as expected. You can set this and it will get correctly set inside PubSubClient however on each MQTT meassage the lengt is compared to MQTT_MAX_PACKET_SIZE but shoud be compared to _mqttClient.getBufferSize()

See line 606:
if (strlen(topic) + length + 9 >= **_mqttClient.getBufferSize()**)

**Comment by plapointe6** [comment]
Thanks for reporting, I corrected it and I will release the fixes soon.

**Comment by plapointe6** [comment]
Fix published with 1.11.0
