### ISSUE TITLE
isMqttConnected returns false always

### ISSUE THREAD

**Issue by steinundfloete** [plapointe6/EspMQTTClient#72]
## Description of the problem
When asking isMqttConnected in loop(), it returns false always, even after onConnectionEstablished was called.
For testing, I implemented onConnectionLost callback the same way as onConnectionEstablished, this works fine.
Would be a nice idea for the next release :), ... same for WiFi (isWifiConnected() works fine)

## Versions

- ESPMQTTClient lib: 1.11.1
- PubSubClient lib: 2.8.0
- Arduino ESP32 / ESP8622 core: v3.2.3-14-gd3e562907

## Hardware
- Board type : ESP32
- Board model : ESP-WROOM-32

**Comment by steinundfloete** [comment]
otherwise.... great work, THANKS A LOT  !!!!

**Comment by plapointe6** [comment]
May be resolved since the last few releases. You can re-open this issue otherwise.
