### ISSUE TITLE
 DelayedMQTTClientConfiguration.ino  not working.

### ISSUE THREAD

**Issue by dmachadol** [plapointe6/EspMQTTClient#88]
## Description of the problem
in line:
EspMQTTClient client;            // using the default constructor

no matching function for call to 'EspMQTTClient::EspMQTTClient()'

## Versions
- ESPMQTTClient lib: -put version number here-

**Comment by davidbeauchamp** [comment]
It appears that there has not been a release since default constructor was added. If you are using the library as installed from the Arduino library manager it will not have the most recent changes. In the interim you can replace the library source with the files from the git repository.

**Comment by plapointe6** [comment]
Sorry for that, I've forgotten to release the last changes.
