### ISSUE TITLE
New esp8266 arduino core 3.0.2 byte issues

### ISSUE THREAD

**Issue by ajaybnl** [plapointe6/EspMQTTClient#89]
Hi,
i have recently updated my arduino 18.x esp8266 core, and found that they have stopped using "Byte".

All the libraries with having Byte variables used will give compilation errors.

Please replace Byte used in your library to Int , as i tested working.

Thanks for a good library.

**Comment by plapointe6** [comment]
Hi,
`Byte` is just a typedef over the type `uint8_t`.
Thanks for pointing this out, I will correct this right away.
