### ISSUE TITLE
onConnectionEstablished setting 

### ISSUE THREAD

**Issue by vbzc** [plapointe6/EspMQTTClient#9]
The onConnectionEstablished setting is removed in the new version. If I need to define two Mqtt objects in the sketch, how do I write onConnectionEstablished code for these two objects? Thank you

**Comment by plapointe6** [comment]
Hi @vbzc 

Can you send me a sample sketch please ?
I want to figure out how it is possible to use two EspMQTTClient in the same sketch ?

It will help me to figure out the best fix for this.

Regards.

**Comment by vbzc** [comment]
Hello, I sent you an email.

**Comment by plapointe6** [comment]
Ok, I see what you want to acheive :)

You want to communicate with two different MQTT broker while being connected to the same WIFI network.

Doing so is a bit unclean with EspMQTTClient as is. It duplicates the wifi handling.

Let me think about the best way to handle that propelly inside the library, I will update when it will be ready for testing.

**Comment by vbzc** [comment]
thank you very much.

Regards

**Comment by plapointe6** [comment]
I made changes in the `dev` branch to allow the use case referenced in this issue plus some memory optimisations. If you are willing I suggest you to try the new changes and let me know if it worked.

See https://github.com/plapointe6/EspMQTTClient/tree/dev for more details.
I've written an exemple to illustrate how to use two MQTT connections in the same sketch.

Take note that I plan to make changes in the `dev` branch soon (for ESP32 support), it is possible that this branch will be less stable.

**Comment by vbzc** [comment]
Thank you for your work, I tested the new features, can work normally, the magic is the second mqtt client, I do not need to set the wifi ssid and password, it can work properly. This is incredible.

**Comment by plapointe6** [comment]
Glad to hear that :)
The news functionalities will be included in the next release.
