### ISSUE TITLE
Implementation of "Check Wifi" and if not connected --> AP + Dialog SSDI+PW

### ISSUE THREAD

**Issue by Hard-n-Soft** [plapointe6/EspMQTTClient#91]
It would be nice to extend the Library by the functionallity to change at least PW+SSID by dialog in AP mode

**Comment by plapointe6** [comment]
Unfortunatly, I don't want to add this to EspMQTTClient. It will make this lib heavier. However, you can use tzapu/WiFiManager and disable the WiFi management from EspMQTTClient.
